import prisma from "../prisma/client.js";
import PDFDocument from "pdfkit";

/*
====================================================
EXPORT EXECUTIVE REPORT (DB DRIVEN)
====================================================
*/

export const exportReport = async (req, res) => {
  try {
    const productions = await prisma.production.findMany({
      include: {
        employee: {
          include: { department: true },
        },
        product: true,
      },
    });

    const employees = await prisma.employee.count();
    const departments = await prisma.department.count();

    let totalUnits = 0;
    let totalDefects = 0;

    productions.forEach((p) => {
      totalUnits += p.units || 0;
      totalDefects += p.defects || 0;
    });

    const efficiency =
      totalUnits > 0
        ? ((totalUnits - totalDefects) / totalUnits) * 100
        : 0;

    /* ================= CREATE PDF ================= */

    const doc = new PDFDocument();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=Industrial_Report.pdf"
    );

    doc.pipe(res);

    doc.fontSize(22).text("Industrial Executive Report", {
      align: "center",
    });

    doc.moveDown();

    doc.fontSize(14).text("System Overview");
    doc.moveDown(0.5);

    doc.text(`Total Employees: ${employees}`);
    doc.text(`Total Departments: ${departments}`);
    doc.text(`Production Records: ${productions.length}`);
    doc.text(`Total Units Produced: ${totalUnits}`);
    doc.text(`Total Defects: ${totalDefects}`);
    doc.text(`Operational Efficiency: ${efficiency.toFixed(2)}%`);

    doc.moveDown(2);

    doc.fontSize(14).text("AI Executive Insight");
    doc.moveDown(0.5);

    if (efficiency >= 85) {
      doc.text(
        "System performance is strong with high operational efficiency and controlled defect rate."
      );
    } else if (efficiency >= 70) {
      doc.text(
        "Moderate efficiency detected. Quality control optimization recommended."
      );
    } else {
      doc.text(
        "Operational risk detected. Immediate review of production workflow required."
      );
    }

    doc.moveDown(2);

    doc.fontSize(12).text("Generated by Industrial DBMS AI Engine");

    doc.end();
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "Report generation failed" });
  }
};